# Use an official Node.js runtime as the base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

RUN npm cache clean --force

# Install dependencies
RUN npm install

# Copy the entire app to the working directory
COPY . .

# Build the React app for production
# RUN npm run build

# Specify the command to run when the container starts
CMD ["npm", "start"]
