"""empty message

Revision ID: 162f59543271
Revises: de8b4ddd1818
Create Date: 2023-04-28 13:03:24.829881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162f59543271'
down_revision = 'de8b4ddd1818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=345), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('folder_id'),
    sa.UniqueConstraint('folder_id'),
    sa.UniqueConstraint('folder_name')
    )
    op.create_table('documents',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ),
    sa.PrimaryKeyConstraint('doc_id', 'doc_name', 'doc_type'),
    sa.UniqueConstraint('doc_id'),
    sa.UniqueConstraint('doc_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('folders')
    # ### end Alembic commands ###
